### ISSUE TITLE
Wink Brutal Test LibXML falure.

### ISSUE THREAD

**Issue by wiwichips** [rafaelwi/SVGhub#8]
Libxml2 fails to open the three Wink_Brutal_Test SVGs. 

Wink_Brutal_Test_1.svg:13: parser error : XML declaration allowed only at the start of the document     <?xml version="1.0" standalone="no"?>                                                                        ^                                                                                                  LIB XML cannot open the file.

**Comment by rafaelwi** [comment]
@xWink move the comments to the bottom, I'll update the CONTRIBUTING guide

**Comment by rafaelwi** [comment]
Fixed in PRs #9, #10, and #11. Fixed and closing...
